{{- if .Values.podCleanUp.active }}
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "spark.fullname" . }}-pod-cleanup
  labels:
    app.kubernetes.io/name: {{ include "spark-history-server.name" . }}
    helm.sh/chart: {{ include "spark.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  schedule: "{{ .Values.podCleanUp.frequency }}"
  jobTemplate:
    spec:
      backoffLimit: 0
      ttlSecondsAfterFinished: 60
      template:
        spec:
          serviceAccountName: {{ include "spark.fullname" . }}-cron
          volumes:
            - name: cleanup-script
              configMap:
                name: cleanup-{{ include "spark.fullname" . }}-pods-script
          containers:
          - name: {{ include "spark.fullname" . }}-pod-cleanup
            image:  apinchuk1/spark-cleanup:1
            command: ["bash", "/mnt/cleanup.sh"]
            volumeMounts:
              - name: cleanup-script
                mountPath: /mnt/
            resources:
              requests:
                cpu: "0.1"
                memory: "10Mi"
              limits:
                cpu: "0.1"
                memory: "10Mi"
          restartPolicy: Never
{{- end }}
