apiVersion: v1
kind: ConfigMap
metadata:
  name: spark-defaults
  labels:
    app.kubernetes.io/name: {{ include "spark-history-server.name" . }}
    helm.sh/chart: {{ include "spark.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
data:
  {{- /*
    Glob files to allow them to be mounted by the hub pod

    spark-defaults.conf: |
      spark.kubernetes.namespace={{ .Release.Namespace }}
      spark.kubernetes.authenticate.driver.serviceAccountName=spark
      spark.kubernetes.container.image={{ .Values.sparkdefaults.image }}
      spark.sql.catalogImplementation=hive
  */}}
