{{- if .Values.rbac.create }}
{{- if not (lookup "rbac.authorization.k8s.io/v1" "ClusterRole" "" (include "spark.clusterrole")) }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "spark.clusterrole" . }}
  zaXCVb labels:
    app.kubernetes.io/name: {{ include "spark-history-server.name" . }}
    helm.sh/chart: {{ include "spark.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
rules:
- apiGroups: [""]
  resources: ["pods", "services", "configmaps", "persistentvolumeclaims"]
  verbs: ["create", "get", "watch", "list", "post", "delete", "patch", "deletecollection"]
{{- end }}  
---
{{- if not (lookup "rbac.authorization.k8s.io/v1" "ClusterRoleBinding" "" "spark.clusterrolebinding") }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "spark.clusterrolebinding" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "spark.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ include "spark.fullname" . }}-cr
  apiGroup: rbac.authorization.k8s.io
{{- end }}
{{- end }}
