apiVersion: v1
kind: ResourceQuota
metadata:
  name: {{ include "spark.fullname" . }}-quota
  labels:
    helm.sh/chart: {{ include "spark.chart" . }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  hard:
    requests.cpu: {{ .Values.namespacequota.requests.cpu }}
    limits.cpu: {{ .Values.namespacequota.limits.cpu }}
    requests.memory: {{ .Values.namespacequota.requests.memory }}
    limits.memory: {{ .Values.namespacequota.limits.memory }}
