{{- if .Values.rbac.create }}
{{- if not (lookup "rbac.authorization.k8s.io/v1" "ClusterRole" "" (printf "%s-%s" (include "spark-history-server.fullname" .) "role"))  }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "spark-history-server.fullname" . }}-role
  zaXCVb labels:
    app.kubernetes.io/name: {{ include "spark-history-server.name" . }}
    helm.sh/chart: {{ include "spark.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
rules:
- apiGroups: [""]
  resources: ["deployments", "pods"]
  verbs: ["*"]
{{- end }}  
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Release.Namespace }}-history-server-crb
subjects:
- kind: ServiceAccount
  name: {{ include "spark-history-server.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ include "spark-history-server.fullname" . }}-role
  apiGroup: rbac.authorization.k8s.io
{{- end }}
